### PR TITLE
Problem: missing update for wc 2.0 api (fix #326)

### LINKED ISSUE #326: Problem: missing update for wc 2.0 api
add wc 2.0 api

### PR DESCRIPTION
**Pull request by leejw51crypto**
upgrade to wc 2.0 api

### CODE REVIEW

**Comment by leejw51crypto** [comment]
fixing ci

**Review by rarcifa — COMMENTED** [review]
Looks like the Build is failing right now. Let me know when it works and I can approve.

**Comment by leejw51crypto** [comment]
because of the security setting, will submit again

**Comment by leejw51crypto** [comment]
it's because pat (github token) expired.
tested
https://github.com/leejw51crypto/play-unreal-plugin/pull/2

waiting to replace pat of the repo

**Comment by rarcifa** [comment]
> 

ok, once the pat is updated and everything we should be good to go

**Comment by leejw51crypto** [comment]
working to replace pat

**Comment by leejw51crypto** [comment]
submit again

**Pull request closed without merging**
