### PR TITLE
Problem: not moving to third party folder (fix #130)

### LINKED ISSUE #130: Problem: not moving to third party folder
move qrcode*, defi-wallet-core* to third party folder
add license notice to source files
check with marketplace guideline

### PR DESCRIPTION
**Pull request by leejw51crypto**
Solution: third party folder refactoring
add license
correct copy
windows ok
add windows library
reformat
update windows
add linux clang lib

### CODE REVIEW

**Review by tomtau — COMMENTED** [review]
should the binaries of qrcodegen library be uploaded to the repo? how does one know it's the expected library, and not something else?

**Comment by tomtau** [comment]
the unreal build fails: https://github.com/cronos-labs/play-unreal-plugin/runs/7852365633?check_suite_focus=true#step:1:33 I guess this needs to be pushed on a branch directly in this repo?

**Comment by leejw51crypto** [comment]
submit again

**Comment by leejw51crypto** [comment]
yes, i'll try to push in cronos repo

**Pull request closed without merging**
